{
 "title": "Plant",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "temp_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_value from testtest1;\n"
    }
   ]
  },
  {
   "title": "moisture_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT moisture_value from testtest1;\n"
    }
   ]
  },
  {
   "title": "motion_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT motion_value from testtest1;\n"
    }
   ]
  },
  {
   "title": "temp_value",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ts, temp_value FROM testtest1;\n"
    }
   ]
  },
  {
   "title": "moisture_value",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ts, moisture_value FROM testtest1;"
    }
   ]
  },
  {
   "title": "motion_value",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ts, motion_value FROM testtest1;"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } }
 ]
}